#!/bin/bash

# assign the action (default launch)
ACTION=${1:-launch}

# display first provided argument (check for emptystring)
if [ -z "$1" ]
	then
		echo "No argument supplied, default action is: $ACTION"
	else
		echo "Initializing $ACTION."
fi

